title: C4process
url: https://c4process.org
description: Collective Code Construction Contract
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
keep_files: [ .domains, LICENSE, CNAME, .git, .gitignore ]
# exclude: [ domains ]
include: [ _pages ]